version: '3.7'

services:

  postgres:
    container_name: postgres-cf-kafka
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  cf-kafka-service-1:
    container_name: cf-kafka-service-1
    image: ere/cf-kafka-service
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: stg
      # todo: env to group
    ports:
      - "8081:8081"

  cf-kafka-service-2:
    container_name: cf-kafka-service-2
    image: ere/cf-kafka-service
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: stg
      # todo: env to group
    ports:
      - "8082:8082"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
