version: '3.7'

services:

  postgres:
    container_name: postgres-default
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  cf-service-1:
    container_name: cf-service-1
    image: ere/cf-service
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: stg
    ports:
      - "8081:8081"

  cf-service-2:
    container_name: cf-service-2
    image: ere/cf-service
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: stg
    ports:
      - "8082:8082"

volumes:
  postgres_data:
